from typing import TypedDict, List, Optional

class AgentState(TypedDict):
    """
    The shared memory clipboard for the Business Research Agent.
    Every agent in the LangGraph workflow reads from and writes to this state.
    """
    # 1. The original user input (e.g., "Analyze Notion's competitors")
    user_input: str
    
    # 2. The classification (e.g., "valid_company", "topic_research", or "invalid_input")
    intent_classification: str
    
    # 3. The step-by-step plan generated by the Planner Agent
    research_plan: List[str]
    
    # 4. Raw data collected by the tools
    search_results: str
    scraped_content: str
    
    # 5. Live logs for the frontend UI (e.g., ["🔍 Searching web...", "🧠 Analyzing data..."])
    live_logs: List[str]
    
    # 6. The final structured JSON output
    final_report: Optional[dict]
    
    # 7. Error messages (if any)
    error: Optional[str]

    raw_analysis: str 